language: node_js
sudo: required
services:
- docker
node_js:
- '10'
script: npm run ci
before_deploy:	
- openssl aes-256-cbc -K $encrypted_98feb76ab7ce_key -iv $encrypted_98feb76ab7ce_iv -in key.enc -out key -d
- docker pull "$DOCKER_USERNAME"/"$IMAGE_NAME" || true	
- docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .	
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"	
- docker tag "$IMAGE_NAME" "$DOCKER_USERNAME/${IMAGE_NAME}:latest"	
- docker push "$DOCKER_USERNAME/${IMAGE_NAME}:latest"
deploy:	
  skip_cleanup: true	
  provider: script	
  script:	
  - chmod 600 key && ssh -o StrictHostKeyChecking=no -i key $SERVER_USER@$SERVER_HOST "cd web/bereg-irkuta && docker-compose pull && docker-compose down && docker-compose up -d"	
  on:	
    branch: master